import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "/playground/testing",
    title: "Playground",
    icon: "bi bi-people",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/category",
    title: "Category",
    icon: "bi bi-people",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard",
    title: "Dashboard",
    icon: "bi bi-speedometer2",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/tour/list",
    title: "Tour",
    icon: "bi bi-people",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/user/list",
    title: "User",
    icon: "bi bi-people",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/agency/list",
    title: "Agency",
    icon: "bi bi-people",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/setting/list",
    title: "Setting",
    icon: "bi bi-wrench",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/alert",
    title: "Alert",
    icon: "bi bi-bell",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/badges",
    title: "Badges",
    icon: "bi bi-patch-check",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/buttons",
    title: "Button",
    icon: "bi bi-hdd-stack",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/card",
    title: "Card",
    icon: "bi bi-card-text",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/dropdown",
    title: "Dropdown",
    icon: "bi bi-menu-app",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/pagination",
    title: "Pagination",
    icon: "bi bi-dice-1",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/nav",
    title: "Nav",
    icon: "bi bi-pause-btn",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/table",
    title: "Table",
    icon: "bi bi-layout-split",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/about",
    title: "About",
    icon: "bi bi-people",
    class: "",
    extralink: false,
    submenu: [],
  },
];
